artifact_uri: file:///home/runner/work/mlops-pipeline-project/mlops-pipeline-project/mlruns/0/c43562bdd03f43029b69ec3b21564300/artifacts
end_time: 1758364545644
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c43562bdd03f43029b69ec3b21564300
run_name: amazing-sow-738
source_name: ''
source_type: 4
source_version: ''
start_time: 1758364543635
status: 3
tags: []
user_id: runner
