artifact_location: file:///home/runner/work/mlops-pipeline-project/mlops-pipeline-project/mlruns/0
creation_time: 1758364543567
experiment_id: '0'
last_update_time: 1758364543567
lifecycle_stage: active
name: Default
