# main.yml (FINAL VERSION - with Deployment to Hugging Face Spaces)

name: Python CI/CD Pipeline to Hugging Face

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Hugging Face Docker Registry
      - name: Log in to Hugging Face Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hf.co
          username: ${{ secrets.HF_USERNAME }}
          password: ${{ secrets.HF_TOKEN }}

      # 3. Build the Docker image AND push it to Hugging Face
      - name: Build and push Docker image to Hugging Face
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # The tag must follow this format: hf.co/{your_hf_username}/{your_space_name}:latest
          tags: hf.co/${{ secrets.HF_USERNAME }}/iris-predictor-app:latest